
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont
import bg_img


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 661, 381))
        self.widget.setObjectName("widget")
        self.bg_label = QtWidgets.QLabel(self.widget)
        self.bg_label.setGeometry(QtCore.QRect(0, 0, 651, 371))
        self.bg_label.setStyleSheet("border-image: url(:/bg/Img/weather background.webp);\n"
"border-radius:10px;")
        self.bg_label.setText("")
        self.bg_label.setObjectName("bg_label")
        self.transparent_label_Sunrise = QtWidgets.QLabel(self.widget)
        self.transparent_label_Sunrise.setGeometry(QtCore.QRect(10, 100, 111, 121))
        self.transparent_label_Sunrise.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label_Sunrise.setText("")
        self.transparent_label_Sunrise.setObjectName("transparent_label_Sunrise")
        self.search_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.search_lineEdit.setGeometry(QtCore.QRect(80, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.search_lineEdit.setFont(font)
        self.search_lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(58,117,175,255);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.search_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.search_pushButton = QtWidgets.QPushButton(self.widget)
        self.search_pushButton.setGeometry(QtCore.QRect(250, 20, 100, 30))
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.505682, 1.0, 0.477)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(85, 98, 150, 230))
        gradient.setColorAt(1.0, QtGui.QColor(85, 98, 185))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.search_pushButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.search_pushButton.setFont(font)
        self.search_pushButton.setStyleSheet("QPushButton#search_pushButton{\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(85,98,150,230), stop:1 rgba(85,98,185,255));\n"
"color:rgba(255,255,,255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#search_pushButton:hover{\n"
"background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(40,67,98,219), stop:1 rgba(105,118,132,226));\n"
"}\n"
"QPushButton#search_pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(105,118,132,200);\n"
"}\n"
"")
        self.search_pushButton.setObjectName("search_pushButton")
        self.sunrise_widget = QtWidgets.QWidget(self.widget)
        self.sunrise_widget.setGeometry(QtCore.QRect(20, 120, 41, 31))
        self.sunrise_widget.setStyleSheet("border-image: url(:/bg/Img/sunrise.png);")
        self.sunrise_widget.setObjectName("sunrise_widget")
        self.sunset_widget = QtWidgets.QWidget(self.widget)
        self.sunset_widget.setGeometry(QtCore.QRect(140, 120, 41, 31))
        self.sunset_widget.setStyleSheet("border-image: url(:/bg/Img/sea.png);")
        self.sunset_widget.setObjectName("sunset_widget")
        self.humidity_widget = QtWidgets.QWidget(self.widget)
        self.humidity_widget.setGeometry(QtCore.QRect(415, 120, 41, 31))
        self.humidity_widget.setStyleSheet("border-image: url(:/bg/Img/humidity.png);\n"
"")
        self.humidity_widget.setObjectName("humidity_widget")
        self.visibility_widget = QtWidgets.QWidget(self.widget)
        self.visibility_widget.setGeometry(QtCore.QRect(540, 120, 41, 31))
        self.visibility_widget.setStyleSheet("border-image: url(:/bg/Img/view.png);")
        self.visibility_widget.setObjectName("visibility_widget")
        self.transparent_label__Sunset = QtWidgets.QLabel(self.widget)
        self.transparent_label__Sunset.setGeometry(QtCore.QRect(130, 100, 111, 121))
        self.transparent_label__Sunset.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label__Sunset.setText("")
        self.transparent_label__Sunset.setObjectName("transparent_label__Sunset")
        self.transparent_label_humidity = QtWidgets.QLabel(self.widget)
        self.transparent_label_humidity.setGeometry(QtCore.QRect(410, 100, 111, 121))
        self.transparent_label_humidity.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label_humidity.setText("")
        self.transparent_label_humidity.setObjectName("transparent_label_humidity")
        self.transparent_label_visibility = QtWidgets.QLabel(self.widget)
        self.transparent_label_visibility.setGeometry(QtCore.QRect(530, 100, 111, 121))
        self.transparent_label_visibility.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label_visibility.setText("")
        self.transparent_label_visibility.setObjectName("transparent_label_visibility")
        self.transparent_label_Temp = QtWidgets.QLabel(self.widget)
        self.transparent_label_Temp.setGeometry(QtCore.QRect(250, 120, 151, 221))
        self.transparent_label_Temp.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label_Temp.setText("")
        self.transparent_label_Temp.setObjectName("transparent_label_Temp")
        self.transparent_label_Pressure = QtWidgets.QLabel(self.widget)
        self.transparent_label_Pressure.setGeometry(QtCore.QRect(10, 240, 111, 121))
        self.transparent_label_Pressure.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label_Pressure.setText("")
        self.transparent_label_Pressure.setObjectName("transparent_label_Pressure")
        self.transparent_label_wind_speed = QtWidgets.QLabel(self.widget)
        self.transparent_label_wind_speed.setGeometry(QtCore.QRect(130, 240, 111, 121))
        self.transparent_label_wind_speed.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label_wind_speed.setText("")
        self.transparent_label_wind_speed.setObjectName("transparent_label_wind_speed")
        self.transparent_label_Air_quality = QtWidgets.QLabel(self.widget)
        self.transparent_label_Air_quality.setGeometry(QtCore.QRect(410, 240, 231, 121))
        self.transparent_label_Air_quality.setStyleSheet("background-color:rgba(0,0,0,30);\n"
"border-radius:10px;")
        self.transparent_label_Air_quality.setText("")
        self.transparent_label_Air_quality.setObjectName("transparent_label_Air_quality")
        self.wind_widget = QtWidgets.QWidget(self.widget)
        self.wind_widget.setGeometry(QtCore.QRect(140, 260, 41, 31))
        self.wind_widget.setStyleSheet("border-image: url(:/bg/Img/compass.png);")
        self.wind_widget.setObjectName("wind_widget")
        self.Pressure_widget = QtWidgets.QWidget(self.widget)
        self.Pressure_widget.setGeometry(QtCore.QRect(20, 260, 41, 31))
        self.Pressure_widget.setStyleSheet("border-image: url(:/bg/Img/Pressure.png);")
        self.Pressure_widget.setObjectName("Pressure_widget")
        self.Sunrise_label = QtWidgets.QLabel(self.widget)
        self.Sunrise_label.setGeometry(QtCore.QRect(20, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sunrise_label.setFont(font)
        self.Sunrise_label.setObjectName("Sunrise_label")
        self.Sunset_label = QtWidgets.QLabel(self.widget)
        self.Sunset_label.setGeometry(QtCore.QRect(140, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Sunset_label.setFont(font)
        self.Sunset_label.setObjectName("Sunset_label")
        self.Pressure_label = QtWidgets.QLabel(self.widget)
        self.Pressure_label.setGeometry(QtCore.QRect(20, 240, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Pressure_label.setFont(font)
        self.Pressure_label.setObjectName("Pressure_label")
        self.wind_label = QtWidgets.QLabel(self.widget)
        self.wind_label.setGeometry(QtCore.QRect(140, 240, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.wind_label.setFont(font)
        self.wind_label.setObjectName("wind_label")
        self.visibility_label = QtWidgets.QLabel(self.widget)
        self.visibility_label.setGeometry(QtCore.QRect(540, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.visibility_label.setFont(font)
        self.visibility_label.setObjectName("visibility_label")
        self.humidity_label = QtWidgets.QLabel(self.widget)
        self.humidity_label.setGeometry(QtCore.QRect(415, 100, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.humidity_label.setFont(font)
        self.humidity_label.setObjectName("humidity_label")
        self.airquality_label = QtWidgets.QLabel(self.widget)
        self.airquality_label.setGeometry(QtCore.QRect(415, 240, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.airquality_label.setFont(font)
        self.airquality_label.setObjectName("airquality_label")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(415, 260, 41, 31))
        self.widget_2.setStyleSheet("border-image: url(:/bg/Img/air_quality.png);")
        self.widget_2.setObjectName("widget_2")

        self.sunrise_text_label = QtWidgets.QLabel(self.widget)
        self.sunrise_text_label.setGeometry(QtCore.QRect(20, 160, 91, 51))
        self.sunrise_text_label.setObjectName("sunrise_text_label")
        self.sunrise_text_label.setFont(QFont("Impact",10))
        self.sunrise_text_label.setStyleSheet("color: #FFFFFF")
        self.sunrise_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.sunset_text_label = QtWidgets.QLabel(self.widget)
        self.sunset_text_label.setGeometry(QtCore.QRect(140, 160, 91, 51))
        self.sunset_text_label.setObjectName("sunset_text_label")
        self.sunset_text_label.setFont(QFont("Impact",10))
        self.sunset_text_label.setStyleSheet("color: #FFFFFF")
        self.sunset_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.pressure_text_label = QtWidgets.QLabel(self.widget)
        self.pressure_text_label.setGeometry(QtCore.QRect(20, 300, 91, 51))
        self.pressure_text_label.setObjectName("pressure_text_label")
        self.pressure_text_label.setFont(QFont("Impact",10))
        self.pressure_text_label.setStyleSheet("color: #FFFFFF")
        self.pressure_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.wind_text_label = QtWidgets.QLabel(self.widget)
        self.wind_text_label.setGeometry(QtCore.QRect(140, 300, 91, 51))
        self.wind_text_label.setObjectName("wind_text_label")
        self.wind_text_label.setFont(QFont("Impact",10))
        self.wind_text_label.setStyleSheet("color: #FFFFFF")
        self.wind_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.humidity_text_label = QtWidgets.QLabel(self.widget)
        self.humidity_text_label.setGeometry(QtCore.QRect(415, 160, 91, 51))
        self.humidity_text_label.setObjectName("humidity_text_label")
        self.humidity_text_label.setFont(QFont("Impact",10))
        self.humidity_text_label.setStyleSheet("color: #FFFFFF")
        self.humidity_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.visibility_text_label = QtWidgets.QLabel(self.widget)
        self.visibility_text_label.setGeometry(QtCore.QRect(540, 160, 91, 51))
        self.visibility_text_label.setObjectName("visibility_text_label")
        self.visibility_text_label.setFont(QFont("Impact",10))
        self.visibility_text_label.setStyleSheet("color: #FFFFFF")
        self.visibility_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.AQI_text_label = QtWidgets.QLabel(self.widget)
        self.AQI_text_label.setGeometry(QtCore.QRect(480, 250, 151, 31))
        self.AQI_text_label.setObjectName("AQI_text_label")
        self.AQI_text_label.setFont(QFont("Impact",12))
        self.AQI_text_label.setStyleSheet("color: #FFFFFF")
        self.AQI_text_label.setAlignment(QtCore.Qt.AlignCenter)

        self.h_temp_text_label = QtWidgets.QLabel(self.widget)
        self.h_temp_text_label.setGeometry(QtCore.QRect(260, 270, 55, 25))
        self.h_temp_text_label.setObjectName("h_temp_text_label")
        self.h_temp_text_label.setFont(QFont("Impact",10))
        self.h_temp_text_label.setStyleSheet("color: #FFFFFF")
        self.h_temp_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.l_temp_text_label = QtWidgets.QLabel(self.widget)
        self.l_temp_text_label.setGeometry(QtCore.QRect(340, 270, 55, 25))
        self.l_temp_text_label.setObjectName("l_temp_text_label")
        self.l_temp_text_label.setFont(QFont("Impact",10))
        self.l_temp_text_label.setStyleSheet("color: #FFFFFF")
        self.l_temp_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.Location_text_label = QtWidgets.QLabel(self.widget)
        self.Location_text_label.setGeometry(QtCore.QRect(260, 130, 131, 41))
        self.Location_text_label.setObjectName("Location_text_label")
        self.Location_text_label.setFont(QFont("Impact",22))
        self.Location_text_label.setStyleSheet("color: #FFFFFF")
        self.Location_text_label.setAlignment(QtCore.Qt.AlignCenter)

        self.temp_text_label = QtWidgets.QLabel(self.widget)
        self.temp_text_label.setGeometry(QtCore.QRect(260, 230, 131, 31))
        self.temp_text_label.setObjectName("temp_text_label")
        self.temp_text_label.setFont(QFont("Impact",15))
        self.temp_text_label.setStyleSheet("color: #FFFFFF")
        self.temp_text_label.setAlignment(QtCore.Qt.AlignCenter)

        self.temp_feellike_text_label = QtWidgets.QLabel(self.widget)
        self.temp_feellike_text_label.setGeometry(QtCore.QRect(260, 300, 131, 25))
        self.temp_feellike_text_label.setObjectName("temp_feellike_text_label")
        self.temp_feellike_text_label.setFont(QFont("Impact",10))
        self.temp_feellike_text_label.setStyleSheet("color: #FFFFFF")
        self.temp_feellike_text_label.setAlignment(QtCore.Qt.AlignCenter)

        self.country_text_label = QtWidgets.QLabel(self.widget)
        self.country_text_label.setGeometry(QtCore.QRect(290, 190, 61, 31))
        self.country_text_label.setObjectName("country_text_label")
        self.country_text_label.setFont(QFont("Impact",17))
        self.country_text_label.setStyleSheet("color: #FFFFFF")
        self.country_text_label.setAlignment(QtCore.Qt.AlignCenter)

        self.CO_text_label = QtWidgets.QLabel(self.widget)
        self.CO_text_label.setGeometry(QtCore.QRect(420, 290, 55, 25))
        self.CO_text_label.setObjectName("CO_text_label")
        self.CO_text_label.setFont(QFont("Impact",7))
        self.CO_text_label.setStyleSheet("color: #FFFFFF")
        self.CO_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.NO_text_label = QtWidgets.QLabel(self.widget)
        self.NO_text_label.setGeometry(QtCore.QRect(420, 320, 55, 25))
        self.NO_text_label.setObjectName("NO_text_label")
        self.NO_text_label.setFont(QFont("Impact",7))
        self.NO_text_label.setStyleSheet("color: #FFFFFF")
        self.NO_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.O3_text_label = QtWidgets.QLabel(self.widget)
        self.O3_text_label.setGeometry(QtCore.QRect(495, 320, 55, 25))
        self.O3_text_label.setObjectName("O3_text_label")
        self.O3_text_label.setFont(QFont("Impact",7))
        self.O3_text_label.setStyleSheet("color: #FFFFFF")
        self.O3_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.NO2_text_label = QtWidgets.QLabel(self.widget)
        self.NO2_text_label.setGeometry(QtCore.QRect(495, 290, 55, 25))
        self.NO2_text_label.setObjectName("NO2_text_label")
        self.NO2_text_label.setFont(QFont("Impact",7))
        self.NO2_text_label.setStyleSheet("color: #FFFFFF")
        self.NO2_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.SO2_text_label = QtWidgets.QLabel(self.widget)
        self.SO2_text_label.setGeometry(QtCore.QRect(575, 290, 55, 25))
        self.SO2_text_label.setObjectName("SO2_text_label")
        self.SO2_text_label.setFont(QFont("Impact",7))
        self.SO2_text_label.setStyleSheet("color: #FFFFFF")
        self.SO2_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.PM25_text_label = QtWidgets.QLabel(self.widget)
        self.PM25_text_label.setGeometry(QtCore.QRect(575, 320, 55, 25))
        self.PM25_text_label.setObjectName("PM25_text_label")
        self.PM25_text_label.setFont(QFont("Impact",7))
        self.PM25_text_label.setStyleSheet("color: #FFFFFF")
        self.PM25_text_label.setAlignment(QtCore.Qt.AlignLeft)

        self.bg_label.raise_()
        self.transparent_label_Sunrise.raise_()
        self.search_lineEdit.raise_()
        self.search_pushButton.raise_()
        self.sunrise_widget.raise_()
        self.transparent_label__Sunset.raise_()
        self.transparent_label_humidity.raise_()
        self.transparent_label_visibility.raise_()
        self.transparent_label_Temp.raise_()
        self.transparent_label_Pressure.raise_()
        self.transparent_label_wind_speed.raise_()
        self.transparent_label_Air_quality.raise_()
        self.wind_widget.raise_()
        self.Pressure_widget.raise_()
        self.Sunrise_label.raise_()
        self.Pressure_label.raise_()
        self.wind_label.raise_()
        self.visibility_widget.raise_()
        self.Sunset_label.raise_()
        self.sunset_widget.raise_()
        self.visibility_label.raise_()
        self.humidity_widget.raise_()
        self.humidity_label.raise_()
        self.airquality_label.raise_()
        self.widget_2.raise_()
        self.sunrise_text_label.raise_()
        self.sunset_text_label.raise_()
        self.pressure_text_label.raise_()
        self.wind_text_label.raise_()
        self.humidity_text_label.raise_()
        self.visibility_text_label.raise_()
        self.Location_text_label.raise_()
        self.temp_text_label.raise_()
        self.country_text_label.raise_()
        self.temp_feellike_text_label.raise_()
        self.l_temp_text_label.raise_()
        self.h_temp_text_label.raise_()
        self.NO2_text_label.raise_()
        self.AQI_text_label.raise_()
        self.PM25_text_label.raise_()
        self.O3_text_label.raise_()
        self.CO_text_label.raise_()
        self.NO_text_label.raise_()
        self.SO2_text_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_lineEdit.setPlaceholderText(_translate("MainWindow", "enter your city here"))
        self.search_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Search</span></p></body></html>"))
        self.search_pushButton.setText(_translate("MainWindow", "Search"))
        self.Sunrise_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">SUNRISE</span></p></body></html>"))
        self.Sunset_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">SUNSET</span></p></body></html>"))
        self.Pressure_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">PRESSURE</span></p></body></html>"))
        self.wind_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">WIND</span></p></body></html>"))
        self.visibility_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">VISIBILITY</span></p></body></html>"))
        self.humidity_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">HUMIDITY</span></p></body></html>"))
        self.airquality_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; color:#ffffff;\">AIR QUALITY (</span><span style=\" font-family:\'JetBrains Mono,monospace\'; font-size:6pt; color:#ffffff;\">µg/m³</span><span style=\" font-size:6pt; color:#ffffff;\">)</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
